// Complete set of realistic sample scholarships across all 8 sectors
const seedScholarships = [
  // =========================================================================
  // 1. EDUCATIONAL SECTOR
  // =========================================================================
  {
    _id: "edu_001",
    name: "PM Yasasvi Higher Education Scheme",
    description: "Financial assistance for meritorious students belonging to OBC, EBC, and DNT categories studying in Class 9th to 12th and Top Class Colleges.",
    eligibility: "Students studying in 12th or first-year Graduation with family income below Rs 2.5 Lakh per annum.",
    sector: "Educational",
    state: "Gujarat",
    category: ["OBC", "EWS"],
    maxIncomeLimit: 600000,
    annualAmount: 125000,
    deadline: "2026-10-30",
    officialLink: "https://yasasvi.nta.ac.in",
    grade: "12th",
    fieldOfStudy: "Science",
    minCGPA: 60,
  },
  {
    _id: "edu_002",
    name: "Central Sector Scheme for College & University Students",
    description: "Scholarship to provide financial support to meritorious students from low-income families to meet their day-to-day expenses while pursuing higher studies.",
    eligibility: "Above 80th percentile of successful candidates in the relevant stream from a recognized Board of Education.",
    sector: "Educational",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 20000,
    deadline: "2026-11-15",
    officialLink: "https://scholarships.gov.in",
    grade: "Bachelor",
    fieldOfStudy: "Engineering",
    minCGPA: 70,
  },
  {
    _id: "edu_003",
    name: "Digital Gujarat Higher Education Post-Matric Scholarship",
    description: "State level scholarship for post-matriculation courses including diploma, degree, and postgraduate programs.",
    eligibility: "Domicile of Gujarat enrolled in recognized degree or diploma program.",
    sector: "Educational",
    state: "Gujarat",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1000000,
    annualAmount: 50000,
    deadline: "2026-12-05",
    officialLink: "https://digitalgujarat.gov.in",
    grade: "Bachelor",
    fieldOfStudy: "Commerce",
    minCGPA: 50,
  },
  {
    _id: "edu_004",
    name: "Pragati Scholarship for Female Engineering Students",
    description: "AICTE scheme providing financial support to young women pursuing technical education in Engineering and Technology.",
    eligibility: "Female students admitted to 1st year of Degree/Diploma course in AICTE approved institutions.",
    sector: "Educational",
    state: "Maharashtra",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 50000,
    deadline: "2026-09-30",
    officialLink: "https://www.aicte-india.org",
    grade: "Bachelor",
    fieldOfStudy: "Engineering",
    minCGPA: 60,
  },
  {
    _id: "edu_005",
    name: "Prime Minister's Research Fellowship (PMRF)",
    description: "Designed for improving the quality of research in various higher educational institutions across India.",
    eligibility: "Completed or in final year of B.Tech/M.Tech with CGPA >= 8.0 or GATE score >= 750.",
    sector: "Educational",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 2000000,
    annualAmount: 960000,
    deadline: "2026-10-15",
    officialLink: "https://pmrf.in",
    grade: "PhD",
    fieldOfStudy: "Engineering",
    minCGPA: 80,
  },

  // =========================================================================
  // 2. SPORTS SECTOR
  // =========================================================================
  {
    _id: "spt_001",
    name: "AAI Sports Talent Search Scholarship",
    description: "Airports Authority of India initiative to encourage young upcoming sports talents by providing monthly stipend and tournament grants.",
    eligibility: "Represented State or Nation in Cricket, Badminton, Athletics or Football.",
    sector: "Sports",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1200000,
    annualAmount: 144000,
    deadline: "2026-10-20",
    officialLink: "https://www.aai.aero",
    sportType: "Cricket",
    performanceLevel: "National Level",
    minAge: 14,
    maxAge: 24,
    ageGroup: "14-18",
  },
  {
    _id: "spt_002",
    name: "Khelo India National Sports Development Fund",
    description: "Comprehensive financial support for equipment, coaching, nutrition, and international exposure for promising young athletes.",
    eligibility: "Podium finish in National Games or top 8 ranking in State Championships.",
    sector: "Sports",
    state: "Rajasthan",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1500000,
    annualAmount: 600000,
    deadline: "2026-11-30",
    officialLink: "https://kheloindia.gov.in",
    sportType: "Athletics",
    performanceLevel: "State Level",
    minAge: 10,
    maxAge: 18,
    ageGroup: "14-18",
  },
  {
    _id: "spt_003",
    name: "Target Olympic Podium Scheme (TOPS) Junior",
    description: "Identify and groom sports talent for 2028 & 2032 Olympic Games with monthly out-of-pocket allowance and customized training.",
    eligibility: "Athletes excelling in Badminton, Swimming, Tennis, or Shooting at International/National level.",
    sector: "Sports",
    state: "Karnataka",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 2000000,
    annualAmount: 300000,
    deadline: "2026-12-15",
    officialLink: "https://sportsauthorityofindia.nic.in",
    sportType: "Badminton",
    performanceLevel: "International Level",
    minAge: 12,
    maxAge: 25,
    ageGroup: "18-25",
  },

  // =========================================================================
  // 3. ARTS & CULTURE SECTOR
  // =========================================================================
  {
    _id: "art_001",
    name: "Cultural Talent Search Scholarship (CCRT)",
    description: "Ministry of Culture scheme to provide specialized training to young children displaying extraordinary talent in fine arts, classical dance, and music.",
    eligibility: "Children in age group of 10 to 14 years studying in recognized schools or practicing under gurus.",
    sector: "Arts & Culture",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 45000,
    deadline: "2026-10-10",
    officialLink: "http://ccrtindia.gov.in",
    artDiscipline: "Classical Music",
    proficiencyLevel: "Intermediate",
    minYearsOfPractice: 2,
  },
  {
    _id: "art_002",
    name: "Sangeet Natak Akademi Young Artists Fellowship",
    description: "Fellowship to support young practitioners in field of Theatre, Puppetry, Folk Performing Arts, and Contemporary Dance.",
    eligibility: "Young performers under 35 years of age with minimum 3 years of performance history.",
    sector: "Arts & Culture",
    state: "Delhi",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1200000,
    annualAmount: 120000,
    deadline: "2026-11-05",
    officialLink: "https://sangeetnatak.gov.in",
    artDiscipline: "Theatre",
    proficiencyLevel: "Advanced",
    minYearsOfPractice: 4,
  },
  {
    _id: "art_003",
    name: "National Visual Arts & Painting Grant",
    description: "Financial grant for emerging painters, sculptors, and digital artists to host exhibitions and purchase raw materials.",
    eligibility: "Art portfolio submission with evidence of past solo or group exhibition participation.",
    sector: "Arts & Culture",
    state: "West Bengal",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1000000,
    annualAmount: 75000,
    deadline: "2026-09-28",
    officialLink: "https://indiaculture.gov.in",
    artDiscipline: "Painting",
    proficiencyLevel: "Professional",
    minYearsOfPractice: 5,
  },

  // =========================================================================
  // 4. HEALTHCARE SECTOR
  // =========================================================================
  {
    _id: "hlth_001",
    name: "Indian Medical Association Merit Healthcare Scholarship",
    description: "Merit-cum-means assistance for underprivileged students pursuing MBBS, BDS, or BHMS degrees in Government Medical Colleges.",
    eligibility: "Valid NEET score above 550 and enrollment in recognized medical college.",
    sector: "Healthcare",
    state: "Tamil Nadu",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 600000,
    annualAmount: 180000,
    deadline: "2026-11-20",
    officialLink: "https://ima-india.org",
    medicalField: "MBBS",
    qualificationLevel: "Undergraduate",
    minNEETScore: 550,
  },
  {
    _id: "hlth_002",
    name: "National Nursing & Allied Health Advancement Grant",
    description: "Financial support for B.Sc and M.Sc Nursing students committing to 2 years of rural healthcare service post graduation.",
    eligibility: "Students registered in recognized Nursing or Physiotherapy institutions with >60% aggregate.",
    sector: "Healthcare",
    state: "Uttar Pradesh",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 60000,
    deadline: "2026-10-25",
    officialLink: "https://main.mohfw.gov.in",
    medicalField: "Nursing",
    qualificationLevel: "Undergraduate",
    minNEETScore: 400,
  },
  {
    _id: "hlth_003",
    name: "AYUSH Ayur-Tech Research & Higher Studies Scholarship",
    description: "Ministry of AYUSH fellowship for Postgraduate and PhD scholars conducting clinical trials in Ayurveda and Herbal Formulations.",
    eligibility: "BAMS/BHMS degree holder pursuing MD/MS (Ayurveda) or PhD.",
    sector: "Healthcare",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1500000,
    annualAmount: 420000,
    deadline: "2026-12-01",
    officialLink: "https://ayush.gov.in",
    medicalField: "Ayurveda",
    qualificationLevel: "Postgraduate",
    minNEETScore: 500,
  },

  // =========================================================================
  // 5. BUSINESS & ENTREPRENEURSHIP SECTOR
  // =========================================================================
  {
    _id: "biz_001",
    name: "Startup India Seed Fund Scheme (SISFS)",
    description: "Financial assistance to early-stage startups for proof of concept, prototype development, product trials, and market entry.",
    eligibility: "DPIIT-recognized startup incorporated less than 2 years ago with innovative technology solution.",
    sector: "Business & Entrepreneurship",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 2500000,
    annualAmount: 2000000,
    deadline: "2026-12-31",
    officialLink: "https://seedfund.startupindia.gov.in",
    businessStage: "Idea",
    businessType: ["Technology", "Healthcare", "Education"],
    fundingAmount: 2000000,
  },
  {
    _id: "biz_002",
    name: "Stand-Up India Women & SC/ST Entrepreneur Fellowship",
    description: "Provides bank loans and grant subsidies between 10 Lakhs to 1 Crore to facilitate greenfield enterprises in manufacturing and services.",
    eligibility: "Women or SC/ST entrepreneurs setting up first-time manufacturing or tech business.",
    sector: "Business & Entrepreneurship",
    state: "Maharashtra",
    category: ["SC", "ST", "General", "OBC", "EWS"],
    maxIncomeLimit: 1500000,
    annualAmount: 1000000,
    deadline: "2026-11-10",
    officialLink: "https://www.standupmitra.in",
    businessStage: "Startup",
    businessType: ["Manufacturing", "Technology", "Retail"],
    fundingAmount: 1000000,
  },
  {
    _id: "biz_003",
    name: "Agri-Tech Youth Innovation Challenge",
    description: "Equity-free grant for young innovators developing solar irrigation, drone tech, or supply chain solutions for Indian farmers.",
    eligibility: "Early growth stage startup with validated pilot implementation.",
    sector: "Business & Entrepreneurship",
    state: "Punjab",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 2000000,
    annualAmount: 500000,
    deadline: "2026-10-18",
    officialLink: "https://agriwelfare.gov.in",
    businessStage: "Growth",
    businessType: ["Agriculture", "Technology", "Energy"],
    fundingAmount: 500000,
  },

  // =========================================================================
  // 6. RESEARCH & INNOVATION SECTOR
  // =========================================================================
  {
    _id: "res_001",
    name: "CSIR-UGC Junior Research Fellowship (JRF)",
    description: "Prestigious national fellowship for pursuing doctoral research in Chemical Sciences, Earth Sciences, Life Sciences, Mathematical & Physical Sciences.",
    eligibility: "Qualified CSIR-NET JRF examination with valid rank.",
    sector: "Research & Innovation",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1500000,
    annualAmount: 444000,
    deadline: "2026-11-25",
    officialLink: "https://csirhrdg.res.in",
    researchField: "Biotechnology",
    researchLevel: "PhD",
    durationMonths: 24,
  },
  {
    _id: "res_002",
    name: "DST WISE-PhD Women in Science Fellowship",
    description: "Department of Science & Technology fellowship aimed at encouraging women researchers to pursue doctoral studies in STEM fields.",
    eligibility: "Women candidates holding Master's degree in Basic or Applied Sciences.",
    sector: "Research & Innovation",
    state: "Delhi",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1200000,
    annualAmount: 372000,
    deadline: "2026-10-31",
    officialLink: "https://dst.gov.in",
    researchField: "AI",
    researchLevel: "PhD",
    durationMonths: 36,
  },
  {
    _id: "res_003",
    name: "National Clean Energy & Quantum Technology Postdoc Grant",
    description: "Postdoctoral grant supporting high-impact research in solar photovoltaics, green hydrogen, and quantum computing.",
    eligibility: "PhD in Physics, Material Science, or Electrical Engineering awarded within last 3 years.",
    sector: "Research & Innovation",
    state: "Karnataka",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 2000000,
    annualAmount: 720000,
    deadline: "2026-12-20",
    officialLink: "https://serb.gov.in",
    researchField: "Clean Energy",
    researchLevel: "Postdoctoral",
    durationMonths: 24,
  },

  // =========================================================================
  // 7. AGRICULTURAL SECTOR
  // =========================================================================
  {
    _id: "agr_001",
    name: "ICAR Junior & Senior Research Fellowship (JRF/SRF)",
    description: "Indian Council of Agricultural Research fellowship for pursuing Master's and PhD degrees in Agriculture, Horticulture, and Forestry.",
    eligibility: "Admission through ICAR All India Entrance Examination for Admission (AIEEA).",
    sector: "Agricultural",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1000000,
    annualAmount: 150000,
    deadline: "2026-11-08",
    officialLink: "https://icar.org.in",
    agriField: "Horticulture",
    agriQualification: "Bachelor",
    farmType: ["Small (<5 acres)", "Medium (5-20)", "Greenhouse"],
  },
  {
    _id: "agr_002",
    name: "Chief Minister's Kisan Youth Agricultural Entrepreneurship Fellowship",
    description: "Stipend and grant scheme to encourage children of marginal farmers to adopt high-tech organic farming and modern dairy practices.",
    eligibility: "Diploma or Bachelor in Agriculture or Allied Sciences with family holding agricultural land.",
    sector: "Agricultural",
    state: "Gujarat",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 600000,
    annualAmount: 120000,
    deadline: "2026-10-12",
    officialLink: "https://dag.gujarat.gov.in",
    agriField: "Organic",
    agriQualification: "Diploma",
    farmType: ["Small (<5 acres)", "Urban Farm"],
  },
  {
    _id: "agr_003",
    name: "National Dairy & Animal Husbandry Advancement Award",
    description: "Financial subsidy for youth establishing modern dairy units, cattle breeding research, or poultry units.",
    eligibility: "Passed minimum 10th/12th grade and completed 15-day certified animal husbandry training.",
    sector: "Agricultural",
    state: "Rajasthan",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 200000,
    deadline: "2026-11-28",
    officialLink: "https://dahd.nic.in",
    agriField: "Dairy",
    agriQualification: "10th/12th",
    farmType: ["Medium (5-20)", "Large (>20)"],
  },

  // =========================================================================
  // 8. SOCIAL SECTOR
  // =========================================================================
  {
    _id: "soc_001",
    name: "TATA Social Welfare & Rural Development Fellowship",
    description: "Two-year intensive fellowship placing young social workers in grassroots development projects across tribal and rural districts.",
    eligibility: "Graduate in Social Work (BSW/MSW), Development Studies, or related humanities disciplines.",
    sector: "Social Sector",
    state: "All States",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1000000,
    annualAmount: 360000,
    deadline: "2026-11-18",
    officialLink: "https://www.tatatrusts.org",
    causeArea: "Rural Dev",
    backgroundRequired: "Social Work degree",
    roleType: "Implementation/Field work",
  },
  {
    _id: "soc_002",
    name: "Azim Premji Foundation Education Grassroots Grant",
    description: "Fellowship for passionate individuals aiming to reform primary government education and teacher training in tier-3 towns.",
    eligibility: "Bachelor's degree in any field with commitment to live and work in rural locations.",
    sector: "Social Sector",
    state: "Rajasthan",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 1200000,
    annualAmount: 420000,
    deadline: "2026-10-28",
    officialLink: "https://azimpremjifoundation.org",
    causeArea: "Education",
    backgroundRequired: "Fresh graduate",
    roleType: "Training",
  },
  {
    _id: "soc_003",
    name: "National Disability Inclusive Leadership & Rights Grant",
    description: "Financial assistance and mentorship for grassroots community leaders advocating for disability rights, accessibility, and rehabilitation.",
    eligibility: "Demonstrated 2+ years of field experience in disability advocacy or inclusive healthcare.",
    sector: "Social Sector",
    state: "Delhi",
    category: ["General", "OBC", "SC", "ST", "EWS"],
    maxIncomeLimit: 800000,
    annualAmount: 250000,
    deadline: "2026-12-10",
    officialLink: "https://disabilityaffairs.gov.in",
    causeArea: "Disability",
    backgroundRequired: "Development experience",
    roleType: "Leadership",
  }
];

module.exports = seedScholarships;
